apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: suraydan/avaliacao:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_PASSWORD
              value: root
            - name: DATABASE_URL
              value: jdbc:mysql://mysql:3306/app_db
            - name: DATABASE_USERNAME
              value: db_usr