apiVersion: v1
kind: Service
metadata:
  name: aplicacao
spec:
  selector:
    app: web
  ports:
    - port: 8080
      targetPort: 3000
      nodePort: 30000
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306